### ISSUE TITLE
Do you have ideas for color?

### ISSUE THREAD

**Issue by ghost** [bitluni/ESP32CompositeVideo#1]
Hello

I read the comments on your Youtube page.

I'm curious to know if any of those comments have given you ideas that might lead to the display in color?

thanks

**Comment by bitluni** [comment]
I read more about the color frequencies.
the PAL frequency is 1/3 of our base frequency that means we could get a color at least on PAL...
I will implement a general solution and a simplified version of PAL non-interlaced
But it will take me another two weeks I guess

**Comment by bootrino** [comment]
Hey there bitluni I have a question for you.

It may be a crazy idea, but what happens when you use both os the I2S ports on the esp32?

Can you drive two screens?

Can you put both signals into a single cable and alternately generate each scan line in the video signal?

Or could you generate image signal from one I2S and color signal from the other I2S?

Maybe crazy ideas but I thought you'd be the one to know.

**Comment by bootrino** [comment]
Ha - I see your new YouTube video uses the second DAC for audio nice one.

When you try to do color, cnlohr had some ideas here for creating a more stable color:

https://github.com/cnlohr/channel3/issues/15

**Comment by marciot** [comment]
I thought you guys might be interested in my [esp32-dali-clock], it is a mishmash between this library and the improved color framebuffer code from [esp_8_bit], which manages to do color in both PAL *and* NTSC. I found it works really well! I made a port of this project called [ESP32CompositeColorVideo] with the associated changes to make it work.

[esp32-dali-clock]: https://github.com/marciot/esp32-dali-clock
[esp_8_bit]: https://github.com/rossumur/esp_8_bit
[ESP32CompositeColorVideo]: https://github.com/marciot/ESP32CompositeColorVideo

**Comment by JyeSmith** [comment]
@marciot colour sounds awesome and something Ill definitely try!  Have you uploaded any demos?

**Comment by marciot** [comment]
@JyeSmith: Yah, click the first hyperlink in my post :)

**Comment by JyeSmith** [comment]
@marciot thanks!  I went straight to the repo for the good stuff.

**Comment by marciot** [comment]
There are two repos, the first is a demo, but there is a bunch of unrelated clock code to dig through, so I also forked this project and added just a simple demo, following @bitluni’s example.
